version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ats_client
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host"]

  server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ats_server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]