version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ats_client
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - server
      
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ats_server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/attendance
    command: ["npm", "start"]
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet"]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    depends_on:
      - mongo

volumes:
  mongo-data:
